/* soapClient.cpp
   Generated by gSOAP 2.8.79 for walabotservice.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.79 2019-02-18 06:36:46 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SensorDoWork(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__SensorDoWork *ns1__SensorDoWork, _ns1__SensorDoWorkResponse &ns1__SensorDoWorkResponse)
{	if (soap_send___ns1__SensorDoWork(soap, soap_endpoint, soap_action, ns1__SensorDoWork) || soap_recv___ns1__SensorDoWork(soap, ns1__SensorDoWorkResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__SensorDoWork(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__SensorDoWork *ns1__SensorDoWork)
{	struct __ns1__SensorDoWork soap_tmp___ns1__SensorDoWork;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/WalabotService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/SensorDoWork";
	soap_tmp___ns1__SensorDoWork.ns1__SensorDoWork = ns1__SensorDoWork;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns1__SensorDoWork(soap, &soap_tmp___ns1__SensorDoWork);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SensorDoWork(soap, &soap_tmp___ns1__SensorDoWork, "-ns1:SensorDoWork", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SensorDoWork(soap, &soap_tmp___ns1__SensorDoWork, "-ns1:SensorDoWork", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__SensorDoWork(struct soap *soap, _ns1__SensorDoWorkResponse &ns1__SensorDoWorkResponse)
{
	ns1__SensorDoWorkResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SensorDoWorkResponse.soap_get(soap, "ns1:SensorDoWorkResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__HelloWorld(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__HelloWorld *ns1__HelloWorld, _ns1__HelloWorldResponse &ns1__HelloWorldResponse)
{	if (soap_send___ns1__HelloWorld(soap, soap_endpoint, soap_action, ns1__HelloWorld) || soap_recv___ns1__HelloWorld(soap, ns1__HelloWorldResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__HelloWorld(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__HelloWorld *ns1__HelloWorld)
{	struct __ns1__HelloWorld soap_tmp___ns1__HelloWorld;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/WalabotService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/HelloWorld";
	soap_tmp___ns1__HelloWorld.ns1__HelloWorld = ns1__HelloWorld;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns1__HelloWorld(soap, &soap_tmp___ns1__HelloWorld);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__HelloWorld(soap, &soap_tmp___ns1__HelloWorld, "-ns1:HelloWorld", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__HelloWorld(soap, &soap_tmp___ns1__HelloWorld, "-ns1:HelloWorld", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__HelloWorld(struct soap *soap, _ns1__HelloWorldResponse &ns1__HelloWorldResponse)
{
	ns1__HelloWorldResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__HelloWorldResponse.soap_get(soap, "ns1:HelloWorldResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SensorDoWork_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__SensorDoWork *ns1__SensorDoWork, _ns1__SensorDoWorkResponse &ns1__SensorDoWorkResponse)
{	if (soap_send___ns1__SensorDoWork_(soap, soap_endpoint, soap_action, ns1__SensorDoWork) || soap_recv___ns1__SensorDoWork_(soap, ns1__SensorDoWorkResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__SensorDoWork_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__SensorDoWork *ns1__SensorDoWork)
{	struct __ns1__SensorDoWork_ soap_tmp___ns1__SensorDoWork_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/WalabotService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/SensorDoWork";
	soap_tmp___ns1__SensorDoWork_.ns1__SensorDoWork = ns1__SensorDoWork;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns1__SensorDoWork_(soap, &soap_tmp___ns1__SensorDoWork_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SensorDoWork_(soap, &soap_tmp___ns1__SensorDoWork_, "-ns1:SensorDoWork", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SensorDoWork_(soap, &soap_tmp___ns1__SensorDoWork_, "-ns1:SensorDoWork", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__SensorDoWork_(struct soap *soap, _ns1__SensorDoWorkResponse &ns1__SensorDoWorkResponse)
{
	ns1__SensorDoWorkResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SensorDoWorkResponse.soap_get(soap, "ns1:SensorDoWorkResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__HelloWorld_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__HelloWorld *ns1__HelloWorld, _ns1__HelloWorldResponse &ns1__HelloWorldResponse)
{	if (soap_send___ns1__HelloWorld_(soap, soap_endpoint, soap_action, ns1__HelloWorld) || soap_recv___ns1__HelloWorld_(soap, ns1__HelloWorldResponse))
		return soap->error;
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___ns1__HelloWorld_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__HelloWorld *ns1__HelloWorld)
{	struct __ns1__HelloWorld_ soap_tmp___ns1__HelloWorld_;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:8080/WalabotService.asmx";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/HelloWorld";
	soap_tmp___ns1__HelloWorld_.ns1__HelloWorld = ns1__HelloWorld;
	soap_begin(soap);
	soap->encodingStyle = NULL; /* use SOAP literal style */
	soap_serializeheader(soap);
	soap_serialize___ns1__HelloWorld_(soap, &soap_tmp___ns1__HelloWorld_);
	if (soap_begin_count(soap))
		return soap->error;
	if ((soap->mode & SOAP_IO_LENGTH))
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__HelloWorld_(soap, &soap_tmp___ns1__HelloWorld_, "-ns1:HelloWorld", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__HelloWorld_(soap, &soap_tmp___ns1__HelloWorld_, "-ns1:HelloWorld", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___ns1__HelloWorld_(struct soap *soap, _ns1__HelloWorldResponse &ns1__HelloWorldResponse)
{
	ns1__HelloWorldResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__HelloWorldResponse.soap_get(soap, "ns1:HelloWorldResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
