/* soapWalabotServiceSoapProxy.h
   Generated by gSOAP 2.8.79 for walabotservice.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapWalabotServiceSoapProxy_H
#define soapWalabotServiceSoapProxy_H
#include "soapH.h"

    class SOAP_CMAC WalabotServiceSoapProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        /// flag indicating that this context is owned by this proxy and should be deleted by the destructor
        bool soap_own;
        /// Endpoint URL of service 'WalabotServiceSoapProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in walabotservice.h, if any
        /// Construct a proxy with new managing context
        WalabotServiceSoapProxy();
        /// Copy constructor
        WalabotServiceSoapProxy(const WalabotServiceSoapProxy& rhs);
        /// Construct proxy given a shared managing context
        WalabotServiceSoapProxy(struct soap*);
        /// Construct proxy given a shared managing context and endpoint URL
        WalabotServiceSoapProxy(struct soap*, const char *soap_endpoint_url);
        /// Constructor taking an endpoint URL
        WalabotServiceSoapProxy(const char *soap_endpoint_url);
        /// Constructor taking input and output mode flags for the new managing context
        WalabotServiceSoapProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        WalabotServiceSoapProxy(const char *soap_endpoint_url, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        WalabotServiceSoapProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and its managing context, when the context was allocated by the contructor
        virtual ~WalabotServiceSoapProxy();
        /// Initializer used by constructors
        virtual void WalabotServiceSoapProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual WalabotServiceSoapProxy *copy();
        /// Copy assignment
        WalabotServiceSoapProxy& operator=(const WalabotServiceSoapProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault subcode QName string (NULL when absent)
        virtual const char *soap_fault_subcode();
        /// Get SOAP Fault string/reason (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail XML string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        //
        /// Web service synchronous operation 'SensorDoWork' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SensorDoWork(_ns1__SensorDoWork *ns1__SensorDoWork, _ns1__SensorDoWorkResponse &ns1__SensorDoWorkResponse) { return this->SensorDoWork(NULL, NULL, ns1__SensorDoWork, ns1__SensorDoWorkResponse); }
        /// Web service synchronous operation 'SensorDoWork' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SensorDoWork(const char *soap_endpoint_url, const char *soap_action, _ns1__SensorDoWork *ns1__SensorDoWork, _ns1__SensorDoWorkResponse &ns1__SensorDoWorkResponse) { return this->send_SensorDoWork(soap_endpoint_url, soap_action, ns1__SensorDoWork) || this->recv_SensorDoWork(ns1__SensorDoWorkResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SensorDoWork' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SensorDoWork(const char *soap_endpoint_url, const char *soap_action, _ns1__SensorDoWork *ns1__SensorDoWork);
        /// Web service asynchronous operation 'recv_SensorDoWork' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SensorDoWork(_ns1__SensorDoWorkResponse &ns1__SensorDoWorkResponse);
        //
        /// Web service synchronous operation 'HelloWorld' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int HelloWorld(_ns1__HelloWorld *ns1__HelloWorld, _ns1__HelloWorldResponse &ns1__HelloWorldResponse) { return this->HelloWorld(NULL, NULL, ns1__HelloWorld, ns1__HelloWorldResponse); }
        /// Web service synchronous operation 'HelloWorld' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int HelloWorld(const char *soap_endpoint_url, const char *soap_action, _ns1__HelloWorld *ns1__HelloWorld, _ns1__HelloWorldResponse &ns1__HelloWorldResponse) { return this->send_HelloWorld(soap_endpoint_url, soap_action, ns1__HelloWorld) || this->recv_HelloWorld(ns1__HelloWorldResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_HelloWorld' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_HelloWorld(const char *soap_endpoint_url, const char *soap_action, _ns1__HelloWorld *ns1__HelloWorld);
        /// Web service asynchronous operation 'recv_HelloWorld' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_HelloWorld(_ns1__HelloWorldResponse &ns1__HelloWorldResponse);
        //
        /// Web service synchronous operation 'SensorDoWork' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int SensorDoWork_(_ns1__SensorDoWork *ns1__SensorDoWork, _ns1__SensorDoWorkResponse &ns1__SensorDoWorkResponse) { return this->SensorDoWork_(NULL, NULL, ns1__SensorDoWork, ns1__SensorDoWorkResponse); }
        /// Web service synchronous operation 'SensorDoWork' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int SensorDoWork_(const char *soap_endpoint_url, const char *soap_action, _ns1__SensorDoWork *ns1__SensorDoWork, _ns1__SensorDoWorkResponse &ns1__SensorDoWorkResponse) { return this->send_SensorDoWork_(soap_endpoint_url, soap_action, ns1__SensorDoWork) || this->recv_SensorDoWork_(ns1__SensorDoWorkResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_SensorDoWork' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_SensorDoWork_(const char *soap_endpoint_url, const char *soap_action, _ns1__SensorDoWork *ns1__SensorDoWork);
        /// Web service asynchronous operation 'recv_SensorDoWork' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_SensorDoWork_(_ns1__SensorDoWorkResponse &ns1__SensorDoWorkResponse);
        //
        /// Web service synchronous operation 'HelloWorld' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int HelloWorld_(_ns1__HelloWorld *ns1__HelloWorld, _ns1__HelloWorldResponse &ns1__HelloWorldResponse) { return this->HelloWorld_(NULL, NULL, ns1__HelloWorld, ns1__HelloWorldResponse); }
        /// Web service synchronous operation 'HelloWorld' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int HelloWorld_(const char *soap_endpoint_url, const char *soap_action, _ns1__HelloWorld *ns1__HelloWorld, _ns1__HelloWorldResponse &ns1__HelloWorldResponse) { return this->send_HelloWorld_(soap_endpoint_url, soap_action, ns1__HelloWorld) || this->recv_HelloWorld_(ns1__HelloWorldResponse) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_HelloWorld' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_HelloWorld_(const char *soap_endpoint_url, const char *soap_action, _ns1__HelloWorld *ns1__HelloWorld);
        /// Web service asynchronous operation 'recv_HelloWorld' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_HelloWorld_(_ns1__HelloWorldResponse &ns1__HelloWorldResponse);
    };
#endif
